### ISSUE TITLE
Feature: User can add a tank

### ISSUE THREAD

**Issue by ellie-hwang** [ellie-hwang/acareum#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add an aquarium tank
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

On the My Aquariums page, user can click the + icon next to the heading to set up a new aquarium tank. The user is then taken to the set up form where they can upload an image of their aquarium from their local files, specify the name of the tank, and specify the size of the tank. On submit, the aquarium is created and a record of the new tank is saved on the database
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![add-tank-mobile](https://user-images.githubusercontent.com/96809909/163627328-69c64663-fa59-48e7-b884-0ab455713ec7.png)
![add-tank-desktop](https://user-images.githubusercontent.com/96809909/163627334-502d5780-ac77-4b34-9c9d-ec3e5d8b0c03.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x]  Make a copy of .env.example named .env.
cp .env.example .env
- [x] Change the DATABASE_URL value to your database’s url
- [x] Install all dependencies with npm install
- [x] Make sure postgresql is running.
sudo service postgresql start
- [x] Export database schema from dbdesigner and paste the sql code into schema.sql
- [x] Write sql code in data.sql to insert some dummy records into the “tanks” table and “images” table
- [x] Create a new database for the project
createdb acareum
- [x] Import the database schema and dummy data with the provided "db:import" script.
npm run db:import
- [x] Start pgweb in a new terminal so you can verify that your data is being updated.
pgweb --db=acareum
- [x] Go to http://localhost:8081/ to make sure the dummy record was inserted into the correct tables

### ☁️ Server

- [x] Create an images directory within the public folder within the server directory. This is where we want the user’s uploaded images to be stored. Store a dummy image into the images directory
- [x] In index.js, require the pg package and create a database connection object (pg.Pool)
- [x] Create a route to POST a record into the images table in the database and a record into the tanks table
- [x] Test the route with HTTPie, send HTTP requests with the POST method with the imageUrl, name, and size parameters

### ⚡ Client

- [x] The client should receive an object. The result could be a 201, 400, or 500. Catch any errors
- [x] Make sure the image file gets store in the images directory
- [x] Create a class component for the My Aquariums page view
- [x] Create a form component with input fields
- [x] When the browse button of the image field is clicked, user should be able to search their local files for an image to upload
- [x] On form submission, client side will use Fetch to create an http request with the POST method. Server will receive request and use the POST route to request data from the database. Database will return data (if any) and the server will serve the data back to the client. 

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
