### ISSUE TITLE
Feature: User can view aquariums

### ISSUE THREAD

**Issue by ellie-hwang** [ellie-hwang/acareum#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a list of their aquariums.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can view a list of their aquariums when the aquarium setup form is submitted OR when they click the "My Aquariums" tab on the sidebar. When the user's cursor hovers on the image of the tank, the aquarium details will be provided (name, population, water conditions)

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![view-aquariums-mobile](https://user-images.githubusercontent.com/96809909/163628973-21e77a6c-caab-41fd-ba9f-577aac670196.png)
![view-aquariums-desktop](https://user-images.githubusercontent.com/96809909/163628976-40e02f7e-2a99-4d6b-8cda-c47ddba724e2.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to include a GET route with the target as '/api/aquariums'
- [x] Send a SQL query to the database for all tank objects, including the name (tanks table), image (images table), conditions (conditions table), and population (aggregate on inhabitants table)
- [x]  When the database sends a response back with records, return the response (results.rows). 
- [x] Catch any errors.
- [x] Test with HTTPie

### ⚡ Client

- [x] Create a component to render the tank images. 
- [x] Create a fetch request with the method as GET to send a HTTP request to the server for the aquarium name, image, conditions, and population (aggregate from inhabitants table).
- [x] Once the client receives a response from the client, store the results in the coomponent's state as an array of of tank objects as the 'tanks' property
- [x] Use a mapping function to render each "tank" object from the response
- [x] onClick, the image container should toggle between showing the tank image and showing the tank details (name, conditions)
- [x] Create a component for the sidebar
- [x] Add a "My Aquariums" tab inside the sidebar
- [x] Add an event listener on the "bars" icon. When the icon is clicked, the side bar should slide out. When the icon is clicked again, the side bar should slide in.
- [x] Create a module to parse the route of the windows.location.hash object. 
- [x] Add a route property within the state property in the constructor method in the app component
- [x] Set the value of route as parseRoute(window.location.hash)
- [x] Add an onhashchange eventlistener within the componentDidMount method of the App component class 
- [x] Add a href property with a value of #tanks to the "My Aquariums" anchor in the side bar
- [x] When the user clicks the "My Aquariums" anchor, the My Aquariums page should be rendered

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
