### ISSUE TITLE
Feature: User can add inhabitant

### ISSUE THREAD

**Issue by ellie-hwang** [ellie-hwang/acareum#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add inhabitant

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

In order to access the inhabitant form, user must be in aquarium's dashboard. The dashboard is accessed by clicking the edit icon on the tank's image preview in the My Aquariums page. In the tank dashboard, there is a section that shows the population count.  Clicking on the section takes the user to the inhabitant form. When the user submits the form, the inhabitant is added to the tank, the user is taken back to the dashboard, and the population section on the dashboard is updated.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![add-inhabitant-mobile-01](https://user-images.githubusercontent.com/96809909/163850178-8d87b60c-aae6-4e55-bc48-9bf3800393cd.png)
![add-inhabitant-mobile-02](https://user-images.githubusercontent.com/96809909/163850181-5aa72338-9b3b-422a-a058-b5cee581ecfc.png)
![add-inhabitant-desktop-01](https://user-images.githubusercontent.com/96809909/163850194-303366d2-f53a-4efb-b340-c21d94acbb58.png)
![add-inhabitant-desktop-02](https://user-images.githubusercontent.com/96809909/163850198-09e8c309-d6b3-42af-81e5-b0ca392dc6c9.png)
![add-inhabitant-desktop-03](https://user-images.githubusercontent.com/96809909/163850199-00f77ebb-0328-4aed-b872-f0d96e7bfb34.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql`, add "species" column to the inhabitants table
- [x] Update `data.sql` to insert dummy inhabitant record

### ☁️ Server

- [x] Update `server/index.js` to include a POST route with target as ('api/inhabitants')
- [x] Send a SQL query to the database to insert into the images table first. Get the imageId and insert into the inhabitants table.
- [x] When the database sends a response back with records, return the response (results.rows[0]).
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Add an edit icon to the tank image preview on the My Aquariums page.
- [x] Add an anchor tag with the href as #dashboard
- [x] When a hash change occurs and the hash location is #dashboard, (clicking the edit icon), render the dashboard
- [x] Create a component to represent the dashboard page
- [x] On the dashboard page, there are two components, the tank image and the population section
- [x] Include a handleClick method in the population section. Clicking on the section changes the hash location to #inhabitantsetup
- [x] Create a form component for the inhabitant
- [x] Submitting the form will send a POST request to the server to add the inhabitant to the database and take the user back to the tank's dashboard
- [x] The population section of the tank's dashboard should update to reflect the current population count.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
