### ISSUE TITLE
Feature: User can view inhabitant

### ISSUE THREAD

**Issue by ellie-hwang** [ellie-hwang/acareum#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view inhabitant
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
When the user is on the tank dashboard, they can click the + icon on the population tab to go to the Inhabitants page. On the Inhabitants page, the user can view a list of the inhabitants residing in the specific tank. When the user clicks the image of the inhabitant, the inhabitant's details (name and species) can be viewed.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![view-inhabitants-mobile](https://user-images.githubusercontent.com/96809909/164109028-2429e5cc-8e9a-4482-ada4-be748560bd64.png)
![view-inhabitants-desktop](https://user-images.githubusercontent.com/96809909/164109029-1b549148-f6c0-4589-b5ca-44387f96aba6.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update server/index.js to include a GET route with the target as '/api/inhabitants/:tankId'
- [x] Send a SQL query to the database for all inhabitant objects, including the name (inhabitants table), species (inhabitants table), and image (images table) where tankId = current tankId
- [x] When the database sends a response back with records, return the response (results.rows).
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to render the inhabitant images.
- [x] Create a fetch request with the method as GET to send a HTTP request to the server for the inhabitant's name, species, and corresponding image.
- [x] Once the client receives a response from the client, store the results in the component's state as an array of inhabitant objects as the 'inhabitants' property
- [x] Use a mapping function to render each "inhabitant" object from the response
- [x] onClick, the image container should toggle between showing the inhabitant image and showing the inhabitant's details (name, species)

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
