### ISSUE TITLE
Feature: User can remove inhabitant

### ISSUE THREAD

**Issue by ellie-hwang** [ellie-hwang/acareum#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can remove inhabitant

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user is on the Inhabitants page they can remove the inhabitant by clicking the inhabitant's image and then clicking the trash icon. Clicking the trash icon opens a modal with a dialogue box asking the user to confirm or cancel their choice. If the user selects cancel, the dialogue box and modal disappear. If the user selects remove, the inhabitant is removed from the inhabitants table and it's corresponding image is also removed from the images table in the database. The user will stay on the Inhabitants page, and the page will no longer show the removed inhabitant.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![remove-inhabitant-mobile](https://user-images.githubusercontent.com/96809909/164513636-d11623c9-665d-481f-ac7c-1dd2e3921157.png)
![remove-inhabitant-desktop-01](https://user-images.githubusercontent.com/96809909/164513639-03e509c6-52cb-45f9-be43-6cdf80533508.png)
![remove-inhabitant-desktop-02](https://user-images.githubusercontent.com/96809909/164513641-b002e55c-2ec9-4e98-8434-f3fab2f8ebd3.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to include DELETE route  with the target as '/api/inhabitants/:inhabitantId'
- [x] Send a SQL query to the database to delete the record from the inhabitants table where inhabitantId = (user provided inhabitantId). Make sure to also delete the corresponding inhabitant image record from the images table.
- [x] When the database sends a response back with records, return the response (results.rows).
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component for the modal and dialogue box. 
- [x] Add an onClick property with a callback function to render the modal component when the user clicks the trash icon
- [x] When the modal component is called. make sure the inhabitant object is passed in as a prop (inhabitant)
- [x] Add an onClick property with a callback function (handleRemove) to the dialogue box. 
- [x] If the target matches the cancel button, hide the modal. If the target matches the remove button, call the fetch method to make a HTTP request to delete the inhabitant and it's corresponding image and send it to the server. 
- [x] Within handleRemove, find the index of the inhabitant that the user wants to remove within the array of inhabitants stored in the state.
- [x] In the fetch call, include the inhabitantId in the target and the imageId in the request body
- [x] Then make a copy of the state's inhabitant's array (slice). Use the index we previously found to remove the inhabitant object from the copy. Assign the updated copy to the state's inhabitant's property.
- [x] Hide the modal
- [x] Ensure that the Inhabitants page does not show the removed inhabitant

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
