### ISSUE TITLE
Feature: User can add aquarium conditions

### ISSUE THREAD

**Issue by ellie-hwang** [ellie-hwang/acareum#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add aquarium conditions.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

On the tank dashboard, there is a H2O Conditions tab. When the user clicks the + icon, they are taken to a form to add a set of  aquarium conditions. When the form is submitted, the set of conditions is added into the conditions database and the user is taken back to the tank dashboard. The H2O Conditions tab should show the most updated conditions.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![add-conditions-mobile](https://user-images.githubusercontent.com/96809909/164830887-80afa7dc-9d32-4e4a-b9f1-98bd172c03f6.PNG)
![add-conditions-desktop-01](https://user-images.githubusercontent.com/96809909/164831048-022bcb8b-4d18-4df4-8505-1c9245bcfa6e.PNG)
![add-conditions-desktop-02](https://user-images.githubusercontent.com/96809909/164831066-3d15cf6b-34a6-41c9-b60a-e7cc085f1c64.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update server/index.js to include a POST route with target as ('api/conditions')
- [x] Send a SQL query to the database to insert into the conditions table. 
- [x] When the database sends a response back with records, return the response (results.rows[0]).
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create the H2O Conditions tab within the Dashboard component. 
- [x] Populate the set of conditions with the most recent water conditions logged
- [x] Add a + icon and surround it with an anchor element with the href as "#conditions-setup
- [x] Create a Conditions form component.
- [x] Add an event listener on the form with a callback function handleSubmit.
- [x] Within handlSubmit, create a fetch call to send a POST request to the server. 
- [x] Assign the hash route `#dashboard?tankId={tankId` to the window.hash.location property. 

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
