### ISSUE TITLE
Feature: User can view charts

### ISSUE THREAD

**Issue by ellie-hwang** [ellie-hwang/acareum#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view charts of individual water condition over the past week or month

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user is on the tank dashboard page, they can access the charts page by clicking on the charts tab. They are then taken to the charts page where the user can select the time span and water condition. The chart will populate and the user will be able to view the chart.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![view-charts-mobile](https://user-images.githubusercontent.com/96809909/166522589-3e36647b-e972-497a-87c9-55fc1bcd9750.PNG)
![view-charts-desktop-01](https://user-images.githubusercontent.com/96809909/166522597-ff742860-6db4-4378-b194-7c43a61dc188.PNG)
![view-charts-desktop-02](https://user-images.githubusercontent.com/96809909/166522598-ba9246fb-fb1a-47b7-9e5f-3db1851367ff.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [ ] Update `data.sql` to hold some dummy data in the conditions table

### ☁️ Server

- [ ] Update `server/index.js` to include some GET routes with targets as ('api/conditions/week/:tankId') and ('api/conditions/month/:tankId')
- [ ] Send a SQL query to the database to get the appropriate data
- [ ]  When the database sends a response back with records, return the response (results.rows).
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Create the Charts tab within the Dashboard component
- [ ] Add a condition to RenderPage() method in the App component that takes the user to the Charts page when the route.path is charts-view
- [ ] Create the ChartsView component to represent the charts page
- [ ] The component should render a placeholder for the chart and two select elements (timespan and condition)
- [ ] Create the Chart component to represent the chart
- [ ] Add an event listener on the form to listen to changes on the select values
- [ ] 
- [ ] With the results, use the Google Charts API to render the chart

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
